openapi: 3.0.3
info:
  title: Process API - Saludos
  description: API orquestadora que combina saludos y mensajes del sistema
  version: 1.0.0
servers:
  - url: http://localhost:8082/api/v1
paths:
  /api/v1/saludos:
    $ref: "paths/v1-saludos.yaml"
